version: '3.7'
services:
  cpu-node:
    build:
      context: .
      dockerfile: Dockerfile
    # 'volumes'maps the src directory in your workspace to the src directory in the container,
    # so that changes to your local files are reflected in the container.
    volumes:
      - ./catkin_ws/src:/app/src
    environment:
      - "ROS_MASTER_URI=http://10.110.177.175:11311"
      # This is the ip of cpu_node. we need this to communicate with nodes in other container
      - "ROS_IP=10.42.0.1"
      - "ROS_PACKAGE_PATH=/app/src"


    # This will override command written in CMD in Dockerfile
    # - ROS launch will run a single ros master and the other nodes stated in all_launch file
    # - We dont need to make a ros master in another container
    # By running source /app/devel/setup.bash, you're setting up the necessary environment variables to use ROS.
    command:  bash -c "source /app/devel/setup.bash && roslaunch cpu all_launch.launch"
    network_mode: host

    # Allow python to print to output immediately
    tty: true
    stdin_open: true
